services:
  php:
    build:
      context: .
      dockerfile: services/dev/php/Dockerfile
    volumes:
      - .:/var/www/imgdock # To reflect local changes to the container
      - php-logs:/var/log/php
    depends_on:
      - mysql
      - minio
      - memcached

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/imgdock/public
      - ./services/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
        - minio-data:/data
    environment:
        MINIO_ROOT_USER: ${MINIO_ROOT_USER}
        MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    entrypoint: sh
    command: >-
      -c '     
        mkdir -p /data/imgdock-dev-storage && 
        minio server /data --console-address :9001'

  memcached:
    image: memcached:alpine
    restart: always
    ports:
      - "11211:11211"
    command: [ "memcached", "-m", "64", "-o", "modern" ]

volumes:
  db-data:
  php-logs:
  minio-data:


