services:
  php:
    image: ${DOCKERHUB_USERNAME}/imgdock-prod:${IMAGE_TAG}
    restart: always
    depends_on:
      - memcached

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/prod/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  memcached:
    image: memcached:alpine
    restart: always
    command: ["-m", "128", "-o", "modern"]
