services:
  php:
    image: ${DOCKERHUB_USERNAME}/imgdock-prod:${IMAGE_TAG}
    restart: always
    volumes:
      - /home/ubuntu/web/imgdock:/var/www/imgdock
    depends_on:
      - memcached

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - /home/ubuntu/web/imgdock:/var/www/imgdock
      - ./services/prod/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  memcached:
    image: memcached:alpine
    restart: always
    command: ["-m", "128", "-o", "modern"]

  https-portal:
    image: steveltn/https-portal:1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "imgdock.com -> http://nginx"
      STAGE: "production"
    volumes:
      - https-portal-data:/var/lib/https-portal

volumes:
  https-portal-data: