services:
  memcached:
    image: memcached:alpine
    restart: always
    command: [ "-m", "128", "-o", "modern" ]

  php:
    image: tkwonn/imgdock-prod:php-latest
    restart: always
    depends_on:
      - memcached
    env_file:
      - .env

  nginx:
    image: tkwonn/imgdock-prod:nginx-latest
    restart: always
    depends_on:
      - php

  https-portal:
    image: steveltn/https-portal:1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "imgdock.com -> http://nginx"
      STAGE: "production"
      CLIENT_MAX_BODY_SIZE: "50M"
    volumes:
      - https-portal-data:/var/lib/https-portal

volumes:
  https-portal-data: