name: deploy to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'public/**'
      - 'src/**'
      - 'services/**'
      - 'compose-prod.yml'
      - '.github/workflows/**'

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-22.04

    env:
      PHP_VERSION: 8.3
      NODE_VERSION: 20.x

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x 🛎
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Cache node modules 📦
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      - name: Install dependencies ⏳
        run: npm ci

      - name: Use PHP 8.3 🛎
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Validate composer.json and composer.lock 👀
        run: composer validate --strict

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer packages 📦
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
            ${{ runner.os }}-

      - name: Install dependencies ⏳
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run PHP CS Fixer 👀
        run: vendor/bin/php-cs-fixer fix -v --diff --dry-run

  build-and-push-docker-images:
    needs: lint
    runs-on: ubuntu-22.04

    env:
      DOCKERHUB_USERNAME: tkwonn

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub 🐳
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image PHP 🚀
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./services/prod/php/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/imgdock-prod:php-${{ github.sha }}
            ${{ env.DOCKERHUB_USERNAME }}/imgdock-prod:php-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image Nginx 🚀
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./services/prod/nginx/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/imgdock-prod:nginx-${{ github.sha }}
            ${{ env.DOCKERHUB_USERNAME }}/imgdock-prod:nginx-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push-docker-images
    runs-on: ubuntu-22.04

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-west-2
      ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ID }}:role/${{ secrets.ROLE_NAME }}
      SESSION_NAME: deploy-${{ github.run_id }}-${{ github.run_attempt }}
      EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
      APP_ENV: prod
      CLOUDFRONT_DOMAIN: ${{ secrets.CLOUDFRONT_DOMAIN }}
      VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
      S3_BUCKET_NAME: imgdock-prod-storage
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_NAME: imgdock
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_USER_PASSWORD: ${{ secrets.DATABASE_USER_PASSWORD }}
      MEMCACHED_HOST: ${{ secrets.MEMCACHED_HOST }}
      MEMCACHED_PORT: ${{ secrets.MEMCACHED_PORT }}

    steps:
      - name: Checkout for logs/scripts
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: ${{ env.SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build static assets ⏳
        run: npm run build

      - name: Sync assets to S3 📂
        run:  |
          aws s3 sync public/assets s3://${{ env.S3_BUCKET_NAME }}/assets --region ${{ env.AWS_REGION }}

      - name: Invalidate CloudFront Cache 🌩
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} \
            --paths "/assets/*" \
            --region ${{ env.AWS_REGION }}

      - name: Deploy via SSM
        shell: bash
        run: |
          cat << 'EOF' > ssm.json
          {
            "commands": [
              "set -e",
              "if [ -d /home/ubuntu/web/imgdock ]; then",
              "  sudo chmod +x /home/ubuntu/web/imgdock/src/bin/cleanup.sh",
              "  sudo /home/ubuntu/web/imgdock/src/bin/cleanup.sh",
              "fi",
              "cd /home/ubuntu/web",
              "git clone https://github.com/tkwonn/imgdock.git",
              "cd /home/ubuntu/web/imgdock",
              "touch .env",  
              "echo APP_ENV=\\\"${{ env.APP_ENV }}\\\" >> .env",
              "echo CLOUDFRONT_DOMAIN=\\\"${{ env.CLOUDFRONT_DOMAIN }}\\\" >> .env",
              "echo VITE_BASE_URL=\\\"${{ env.VITE_BASE_URL }}\\\" >> .env",
              "echo S3_BUCKET_NAME=\\\"${{ env.S3_BUCKET_NAME }}\\\" >> .env",
              "echo DATABASE_HOST=\\\"${{ env.DATABASE_HOST }}\\\" >> .env",
              "echo DATABASE_NAME=\\\"${{ env.DATABASE_NAME }}\\\" >> .env",
              "echo DATABASE_USER=\\\"${{ env.DATABASE_USER }}\\\" >> .env",
              "echo DATABASE_USER_PASSWORD=\\\"${{ env.DATABASE_USER_PASSWORD }}\\\" >> .env",
              "echo MEMCACHED_HOST=\\\"${{ env.MEMCACHED_HOST }}\\\" >> .env",
              "echo MEMCACHED_PORT=\\\"${{ env.MEMCACHED_PORT }}\\\" >> .env",
              "sudo chmod +x /home/ubuntu/web/imgdock/src/bin/db_backup.sh",
              "sudo docker-compose -f compose-prod.yml up -d --pull always"
            ]
          }
          EOF

          echo "======= ssm.json ======="
          cat ssm.json
          echo "========================"

          COMMANDS_JSON=$(cat ssm.json)

          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "${{ env.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy application" \
            --parameters "$COMMANDS_JSON" \
            --region "${{ env.AWS_REGION }}" \
            --timeout-seconds 3600 \
            --query "Command.CommandId" \
            --output text)

          echo "SSM Command ID: $COMMAND_ID"

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "${{ env.EC2_INSTANCE_ID }}" \
            --region "${{ env.AWS_REGION }}" || {
              echo "SSM command failed or timed out."
              aws ssm get-command-invocation \
                --instance-id "${{ env.EC2_INSTANCE_ID }}" \
                --command-id "$COMMAND_ID" \
                --region "${{ env.AWS_REGION }}" \
                --query "StandardErrorContent" \
                --output text
              exit 1
            }

          OUTPUT=$(aws ssm get-command-invocation \
            --instance-id "${{ env.EC2_INSTANCE_ID }}" \
            --command-id "$COMMAND_ID" \
            --region "${{ env.AWS_REGION }}" \
            --query "StandardOutputContent" \
            --output text)

          echo "[INFO] SSM Command Output:"
          echo "$OUTPUT"